version: 2
updates:
  - package-ecosystem: pip
    directory: /django
    schedule:
      interval: weekly
    groups:
      pip-minor-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: /react-app
    schedule:
      interval: weekly
    groups:
      npm-minor-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: maven
    directory: /springboot
    schedule:
      interval: weekly
    groups:
      maven-minor-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: docker
    directories:
      - /django
      - /springboot
      - /nginx
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
