# Generated by Django 5.0.4 on 2024-12-08 01:43

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=1000)),
                ('marketCap', models.DecimalField(decimal_places=0, max_digits=100)),
                ('volume', models.DecimalField(decimal_places=0, default=0, max_digits=100)),
                ('volumeUSD', models.DecimalField(decimal_places=0, default=0, max_digits=100)),
                ('freeFloat', models.DecimalField(decimal_places=5, default=100, max_digits=100)),
                ('freeFloatMarketCap', models.DecimalField(decimal_places=0, default=0, max_digits=100)),
                ('countryIncorp', models.CharField(default='United States', max_length=1000)),
                ('countryHQ', models.CharField(default='United States', max_length=1000)),
                ('securityType', models.CharField(default='Common Stock', max_length=1000)),
                ('yearIPO', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalStock',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('ticker', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=1000)),
                ('marketCap', models.DecimalField(decimal_places=0, max_digits=100)),
                ('volume', models.DecimalField(decimal_places=0, default=0, max_digits=100)),
                ('volumeUSD', models.DecimalField(decimal_places=0, default=0, max_digits=100)),
                ('freeFloat', models.DecimalField(decimal_places=5, default=100, max_digits=100)),
                ('freeFloatMarketCap', models.DecimalField(decimal_places=0, default=0, max_digits=100)),
                ('countryIncorp', models.CharField(default='United States', max_length=1000)),
                ('countryHQ', models.CharField(default='United States', max_length=1000)),
                ('securityType', models.CharField(default='Common Stock', max_length=1000)),
                ('yearIPO', models.IntegerField(default=0)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical stock',
                'verbose_name_plural': 'historical stocks',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='IndexMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.DecimalField(decimal_places=5, max_digits=100)),
                ('index', models.CharField(max_length=1000)),
                ('outlier', models.BooleanField(default=False)),
                ('notes', models.CharField(default='', max_length=100000)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexes.stock')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalIndexMember',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('percent', models.DecimalField(decimal_places=5, max_digits=100)),
                ('index', models.CharField(max_length=1000)),
                ('outlier', models.BooleanField(default=False)),
                ('notes', models.CharField(default='', max_length=100000)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('stock', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexes.stock')),
            ],
            options={
                'verbose_name': 'historical index member',
                'verbose_name_plural': 'historical index members',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
