services:
# Django/Gunicorn web Server
  django:
    build: ./django
    #container_name: django
    expose:
      - "8000"

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - django