services:
# Django/Gunicorn web Server
  django:
    build: ./django
    container_name: django
    image: django
    # environment:
      # secretKey: django-insecure-f^jq_nh_i2bgw&c_dhmq^k-f5ohphk@9mk(_@#=z+$8vo0^v4+
    ports:
      - 8000:8000

    depends_on:
      - postgres

  nginx:
    build: ./nginx
    container_name: nginx
    image: nginx
    ports:
      - 1337:1337
    depends_on:
      - django
  
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres

    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports: 
      - 5432:5432
    # expose:
    #  - "5432"

volumes:
  postgres_data: