services:
# Django/Gunicorn web Server
  django:
    build: ./django
    container_name: django
    image: 196185437114.dkr.ecr.us-east-1.amazonaws.com/django
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
    ports:
      - 8000:8000
    #expose:
    #  - 8000

    depends_on:
      - postgres

  nginx:
    build: ./nginx
    container_name: nginx
    image: 196185437114.dkr.ecr.us-east-1.amazonaws.com/nginx
    ports:
     - 80:80
    depends_on:
      - django
  
  postgres:
    build: ./postgres
    container_name: postgres
    image: 196185437114.dkr.ecr.us-east-1.amazonaws.com/postgres
    environment:
      POSTGRES_PASSWORD: postgres

    volumes:
      - postgres_data:/var/lib/postgresql/data
    # ports: 
    #  - 5432:5432
    expose:
      - 5432

volumes:
  postgres_data: