version: '3.8'

services:
  django:
    build:
      context: .
      dockerfile: django/Dockerfile
    image: johnfattore/django

  celery:
    build:
      context: .
      dockerfile: celery/Dockerfile
    image: johnfattore/celery