# Generated by Django 4.1.4 on 2022-12-18 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ETF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker_text', models.CharField(max_length=4)),
                ('shares_integer', models.IntegerField()),
                ('costbasis_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buy_date', models.DateTimeField(verbose_name='date bought')),
            ],
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker_text', models.CharField(max_length=4)),
                ('shares_integer', models.IntegerField()),
                ('costbasis_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buy_date', models.DateTimeField(verbose_name='date bought')),
            ],
        ),
    ]
