# Generated by Django 4.1.4 on 2023-01-03 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker_text', models.CharField(max_length=5)),
                ('shares_integer', models.DecimalField(decimal_places=5, max_digits=10)),
                ('costbasis_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buy_date', models.DateField(verbose_name='date bought')),
                ('account', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
