# Generated by Django 4.1.4 on 2023-01-06 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker_text', models.CharField(max_length=5)),
                ('shares_integer', models.DecimalField(decimal_places=5, max_digits=10)),
                ('currentPrice', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
