# Generated by Django 4.1.4 on 2022-12-23 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_rename_stocks_stock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ETF',
        ),
        migrations.AlterField(
            model_name='stock',
            name='shares_integer',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
