# Generated by Django 4.1.4 on 2023-02-03 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_allocation_percent_allocated'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='target',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
