# Generated by Django 4.1.7 on 2023-10-29 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_userinfo_rename_account_asset_account_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='costbasis_price',
            new_name='costbasis_number',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='shares_integer',
            new_name='shares_number',
        ),
    ]
