# Generated by Django 4.1.7 on 2023-10-31 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_rename_costbasis_price_asset_costbasis_number_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Allocation',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='account_text',
            new_name='account_string',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='ticker_text',
            new_name='ticker_string',
        ),
    ]
