# Generated by Django 5.0.4 on 2024-12-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_remove_favorite_restaurant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalfavorite',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
