# Generated by Django 5.0.4 on 2025-01-08 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_favorite_comment_historicalfavorite_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalreview',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 - Poor'), (1.5, '1.5 - Subpar'), (2, '2 - Fair'), (2.5, '2.5 - Almost Good'), (3, '3 - Good'), (3.5, '3.5 - Decent'), (4, '4 - Very Good'), (4.5, '4.5 - Excellent-ish'), (5, '5 - Excellent')]),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 - Poor'), (1.5, '1.5 - Subpar'), (2, '2 - Fair'), (2.5, '2.5 - Almost Good'), (3, '3 - Good'), (3.5, '3.5 - Decent'), (4, '4 - Very Good'), (4.5, '4.5 - Excellent-ish'), (5, '5 - Excellent')]),
        ),
    ]
