# Generated by Django 5.0.4 on 2025-01-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_alter_historicalreview_rating_alter_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalrestaurant',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='historicalrestaurant',
            name='website',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='website',
        ),
        migrations.AddField(
            model_name='historicalrestaurant',
            name='categories',
            field=models.TextField(default='eat'),
        ),
        migrations.AddField(
            model_name='historicalrestaurant',
            name='city',
            field=models.TextField(default='NA'),
        ),
        migrations.AddField(
            model_name='historicalrestaurant',
            name='latitude',
            field=models.DecimalField(decimal_places=8, default=1, max_digits=25),
        ),
        migrations.AddField(
            model_name='historicalrestaurant',
            name='longitude',
            field=models.DecimalField(decimal_places=8, default=1, max_digits=25),
        ),
        migrations.AddField(
            model_name='historicalrestaurant',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalrestaurant',
            name='stars',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 - Poor'), (1.5, '1.5 - Subpar'), (2, '2 - Fair'), (2.5, '2.5 - Almost Good'), (3, '3 - Good'), (3.5, '3.5 - Decent'), (4, '4 - Very Good'), (4.5, '4.5 - Excellent-ish'), (5, '5 - Excellent')], default=1),
        ),
        migrations.AddField(
            model_name='historicalrestaurant',
            name='state',
            field=models.TextField(default='Nash'),
        ),
        migrations.AddField(
            model_name='historicalrestaurant',
            name='yelp_id',
            field=models.CharField(default=1, max_length=250),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='categories',
            field=models.TextField(default='eat'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='city',
            field=models.TextField(default='NA'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='latitude',
            field=models.DecimalField(decimal_places=8, default=1, max_digits=25),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='longitude',
            field=models.DecimalField(decimal_places=8, default=1, max_digits=25),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='stars',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 - Poor'), (1.5, '1.5 - Subpar'), (2, '2 - Fair'), (2.5, '2.5 - Almost Good'), (3, '3 - Good'), (3.5, '3.5 - Decent'), (4, '4 - Very Good'), (4.5, '4.5 - Excellent-ish'), (5, '5 - Excellent')], default=1),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='state',
            field=models.TextField(default='Nash'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='yelp_id',
            field=models.CharField(default=1, max_length=250),
        ),
    ]
