# Generated by Django 5.0.4 on 2025-01-18 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_remove_historicalrestaurant_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalrestaurant',
            name='stars',
            field=models.DecimalField(choices=[(1, '1 - Poor'), (1.5, '1.5 - Subpar'), (2, '2 - Fair'), (2.5, '2.5 - Almost Good'), (3, '3 - Good'), (3.5, '3.5 - Decent'), (4, '4 - Very Good'), (4.5, '4.5 - Excellent-ish'), (5, '5 - Excellent')], decimal_places=1, default=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='stars',
            field=models.DecimalField(choices=[(1, '1 - Poor'), (1.5, '1.5 - Subpar'), (2, '2 - Fair'), (2.5, '2.5 - Almost Good'), (3, '3 - Good'), (3.5, '3.5 - Decent'), (4, '4 - Very Good'), (4.5, '4.5 - Excellent-ish'), (5, '5 - Excellent')], decimal_places=1, default=1, max_digits=2),
        ),
    ]
