# Generated by Django 5.0.4 on 2025-01-18 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_alter_historicalrestaurant_stars_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalreview',
            old_name='restaurant',
            new_name='Restaurant',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='restaurant',
            new_name='Restaurant',
        ),
    ]
