# Generated by Django 5.0.4 on 2025-01-18 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_rename_restaurant_historicalreview_restaurant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalreview',
            old_name='Restaurant',
            new_name='restaurant',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='Restaurant',
            new_name='restaurant',
        ),
    ]
