# Generated by Django 5.0.4 on 2026-02-12 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changeflow', '0002_historicalchangerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='changerequest',
            name='solution',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalchangerequest',
            name='solution',
            field=models.TextField(blank=True),
        ),
    ]
