# Generated by Django 4.1.7 on 2024-03-24 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallstreet', '0002_remove_selection_sunday'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='endPrice',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=10),
        ),
        migrations.AddField(
            model_name='option',
            name='rank',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='option',
            name='startPrice',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=10),
        ),
    ]
