# Generated by Django 4.1.7 on 2024-03-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallstreet', '0003_option_endprice_option_rank_option_startprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='endPrice',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='option',
            name='rank',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='option',
            name='startPrice',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
