# Generated by Django 4.1.7 on 2024-03-30 02:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallstreet', '0007_selection_allocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AltBenchMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benchmark', models.CharField(max_length=256)),
                ('percentChange', models.DecimalField(decimal_places=2, default=2, max_digits=10)),
                ('sunday', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='UserWeeklyResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolioPercentChange', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('sunday', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='WeeklyResults',
        ),
    ]
