# Generated by Django 4.1.7 on 2024-03-30 17:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallstreet', '0008_altbenchmarks_userweeklyresults_delete_weeklyresults'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AltBenchMarks',
            new_name='AltBenchMark',
        ),
        migrations.RenameModel(
            old_name='UserWeeklyResults',
            new_name='UserWeeklyResult',
        ),
    ]
