# Generated by Django 5.0.4 on 2024-04-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallstreet', '0011_delete_altbenchmark_option_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='name',
            field=models.CharField(max_length=1000),
        ),
    ]
