-- Initial schema generated from Hibernate (entities + Envers audit tables).
-- Dumped from database version 14.22 (Ubuntu 14.22-0ubuntu0.22.04.1)
-- Dumped by pg_dump version 14.22 (Ubuntu 14.22-0ubuntu0.22.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: assets; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.assets (
    is_fund boolean,
    cik bigint NOT NULL,
    id bigint NOT NULL
);


--
-- Name: assets_aud; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.assets_aud (
    is_fund boolean,
    rev integer NOT NULL,
    revtype smallint,
    cik bigint,
    id bigint NOT NULL
);


--
-- Name: assets_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.assets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.assets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: corporate_actions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.corporate_actions (
    adjusted_dividend double precision,
    confidence_score double precision,
    effective_date date NOT NULL,
    pay_date date,
    ratio double precision NOT NULL,
    raw_dividend double precision,
    record_date date,
    id bigint NOT NULL,
    action_type character varying(10) NOT NULL,
    ticker character varying(10) NOT NULL,
    form_type character varying(20),
    sec_class_contract_id character varying(32),
    sec_series_id character varying(32),
    source_type character varying(32),
    accession_number character varying(40),
    CONSTRAINT corporate_actions_action_type_check CHECK (((action_type)::text = ANY ((ARRAY['SPLIT'::character varying, 'DIVIDEND'::character varying])::text[]))),
    CONSTRAINT corporate_actions_source_type_check CHECK (((source_type)::text = ANY ((ARRAY['SEC_EQUITY_XBRL'::character varying, 'SEC_ETF_FILING'::character varying, 'MANUAL'::character varying, 'OTHER'::character varying])::text[])))
);


--
-- Name: corporate_actions_aud; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.corporate_actions_aud (
    adjusted_dividend double precision,
    confidence_score double precision,
    effective_date date,
    pay_date date,
    ratio double precision,
    raw_dividend double precision,
    record_date date,
    rev integer NOT NULL,
    revtype smallint,
    id bigint NOT NULL,
    action_type character varying(10),
    ticker character varying(10),
    form_type character varying(20),
    sec_class_contract_id character varying(32),
    sec_series_id character varying(32),
    source_type character varying(32),
    accession_number character varying(40),
    CONSTRAINT corporate_actions_aud_action_type_check CHECK (((action_type)::text = ANY ((ARRAY['SPLIT'::character varying, 'DIVIDEND'::character varying])::text[]))),
    CONSTRAINT corporate_actions_aud_source_type_check CHECK (((source_type)::text = ANY ((ARRAY['SEC_EQUITY_XBRL'::character varying, 'SEC_ETF_FILING'::character varying, 'MANUAL'::character varying, 'OTHER'::character varying])::text[])))
);


--
-- Name: corporate_actions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.corporate_actions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.corporate_actions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: daily_prices; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.daily_prices (
    adjusted_close double precision,
    adjusted_high double precision,
    adjusted_low double precision,
    adjusted_open double precision,
    close_price double precision,
    high_price double precision,
    low_price double precision,
    open_price double precision,
    trade_date date NOT NULL,
    id bigint NOT NULL,
    volume bigint,
    ticker character varying(10) NOT NULL
);


--
-- Name: daily_prices_aud; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.daily_prices_aud (
    adjusted_close double precision,
    adjusted_high double precision,
    adjusted_low double precision,
    adjusted_open double precision,
    close_price double precision,
    high_price double precision,
    low_price double precision,
    open_price double precision,
    rev integer NOT NULL,
    revtype smallint,
    trade_date date,
    id bigint NOT NULL,
    volume bigint,
    ticker character varying(10)
);


--
-- Name: daily_prices_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.daily_prices_id_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: filing_summaries; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.filing_summaries (
    filing_date date NOT NULL,
    asset_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    ticker character varying(10) NOT NULL,
    accession_number character varying(30) NOT NULL,
    raw_text text,
    summary text
);


--
-- Name: filing_summaries_aud; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.filing_summaries_aud (
    filing_date date,
    rev integer NOT NULL,
    revtype smallint,
    asset_id bigint,
    created_at timestamp(6) without time zone,
    id bigint NOT NULL,
    ticker character varying(10),
    accession_number character varying(30),
    raw_text text,
    summary text
);


--
-- Name: filing_summaries_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.filing_summaries ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.filing_summaries_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: index_members; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.index_members (
    outlier boolean NOT NULL,
    percent numeric(38,5) NOT NULL,
    id bigint NOT NULL,
    listing_id bigint NOT NULL,
    market_index_id bigint NOT NULL,
    notes character varying(100000)
);


--
-- Name: index_members_aud; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.index_members_aud (
    outlier boolean,
    percent numeric(38,5),
    rev integer NOT NULL,
    revtype smallint,
    id bigint NOT NULL,
    listing_id bigint,
    market_index_id bigint,
    notes character varying(100000)
);


--
-- Name: index_members_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.index_members ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.index_members_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: listing_index_metrics; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.listing_index_metrics (
    free_float numeric(38,5),
    free_float_market_cap numeric(38,5),
    market_cap numeric(38,5),
    volume numeric(38,5),
    volume_usd numeric(38,5),
    year integer NOT NULL,
    year_ipo integer,
    id bigint NOT NULL,
    listing_id bigint NOT NULL,
    country_hq character varying(1000),
    country_incorp character varying(1000),
    security_type character varying(1000),
    state_hq character varying(1000),
    state_incorp character varying(1000)
);


--
-- Name: listing_index_metrics_aud; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.listing_index_metrics_aud (
    free_float numeric(38,5),
    free_float_market_cap numeric(38,5),
    market_cap numeric(38,5),
    rev integer NOT NULL,
    revtype smallint,
    volume numeric(38,5),
    volume_usd numeric(38,5),
    year integer,
    year_ipo integer,
    id bigint NOT NULL,
    listing_id bigint,
    country_hq character varying(1000),
    country_incorp character varying(1000),
    security_type character varying(1000),
    state_hq character varying(1000),
    state_incorp character varying(1000)
);


--
-- Name: listing_index_metrics_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.listing_index_metrics ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.listing_index_metrics_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: listings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.listings (
    asset_id bigint,
    id bigint NOT NULL,
    ticker character varying(10) NOT NULL,
    sec_class_ticker character varying(16),
    sec_identity_status character varying(24),
    sec_class_contract_id character varying(32),
    sec_series_id character varying(32),
    title character varying(100) NOT NULL,
    sec_class_name character varying(255),
    sec_series_name character varying(255)
);


--
-- Name: listings_aud; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.listings_aud (
    rev integer NOT NULL,
    revtype smallint,
    asset_id bigint,
    id bigint NOT NULL,
    ticker character varying(10),
    sec_class_ticker character varying(16),
    sec_identity_status character varying(24),
    sec_class_contract_id character varying(32),
    sec_series_id character varying(32),
    title character varying(100),
    sec_class_name character varying(255),
    sec_series_name character varying(255)
);


--
-- Name: listings_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.listings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.listings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: market_indexes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.market_indexes (
    id bigint NOT NULL,
    code character varying(64) NOT NULL,
    display_name character varying(500) NOT NULL
);


--
-- Name: market_indexes_aud; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.market_indexes_aud (
    rev integer NOT NULL,
    revtype smallint,
    id bigint NOT NULL,
    code character varying(64),
    display_name character varying(500)
);


--
-- Name: market_indexes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.market_indexes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.market_indexes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: quarters; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.quarters (
    earnings_per_share_basic double precision,
    earnings_per_share_diluted double precision,
    period_end date,
    period_start date,
    quarter integer,
    year integer,
    accounts_receivable_net_current bigint,
    asset_id bigint,
    assets bigint,
    cash_and_cash_equivalents_at_carrying_value bigint,
    gross_profit bigint,
    id bigint NOT NULL,
    inventory_net bigint,
    liabilities bigint,
    net_cash_provided_by_used_in_operating_activities bigint,
    net_income_loss bigint,
    operating_income_loss bigint,
    payments_for_repurchase_of_common_stock bigint,
    payments_of_dividends bigint,
    revenues bigint,
    stockholders_equity bigint
);


--
-- Name: quarters_aud; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.quarters_aud (
    earnings_per_share_basic double precision,
    earnings_per_share_diluted double precision,
    period_end date,
    period_start date,
    quarter integer,
    rev integer NOT NULL,
    revtype smallint,
    year integer,
    accounts_receivable_net_current bigint,
    asset_id bigint,
    assets bigint,
    cash_and_cash_equivalents_at_carrying_value bigint,
    gross_profit bigint,
    id bigint NOT NULL,
    inventory_net bigint,
    liabilities bigint,
    net_cash_provided_by_used_in_operating_activities bigint,
    net_income_loss bigint,
    operating_income_loss bigint,
    payments_for_repurchase_of_common_stock bigint,
    payments_of_dividends bigint,
    revenues bigint,
    stockholders_equity bigint
);


--
-- Name: quarters_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.quarters ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.quarters_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: revinfo; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.revinfo (
    rev integer NOT NULL,
    revtstmp bigint
);


--
-- Name: revinfo_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.revinfo_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: assets_aud assets_aud_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assets_aud
    ADD CONSTRAINT assets_aud_pkey PRIMARY KEY (rev, id);


--
-- Name: assets assets_cik_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assets
    ADD CONSTRAINT assets_cik_key UNIQUE (cik);


--
-- Name: assets assets_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assets
    ADD CONSTRAINT assets_pkey PRIMARY KEY (id);


--
-- Name: corporate_actions_aud corporate_actions_aud_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.corporate_actions_aud
    ADD CONSTRAINT corporate_actions_aud_pkey PRIMARY KEY (rev, id);


--
-- Name: corporate_actions corporate_actions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.corporate_actions
    ADD CONSTRAINT corporate_actions_pkey PRIMARY KEY (id);


--
-- Name: corporate_actions corporate_actions_ticker_action_type_effective_date_ratio_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.corporate_actions
    ADD CONSTRAINT corporate_actions_ticker_action_type_effective_date_ratio_key UNIQUE (ticker, action_type, effective_date, ratio);


--
-- Name: daily_prices_aud daily_prices_aud_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.daily_prices_aud
    ADD CONSTRAINT daily_prices_aud_pkey PRIMARY KEY (rev, id);


--
-- Name: daily_prices daily_prices_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.daily_prices
    ADD CONSTRAINT daily_prices_pkey PRIMARY KEY (id);


--
-- Name: daily_prices daily_prices_ticker_trade_date_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.daily_prices
    ADD CONSTRAINT daily_prices_ticker_trade_date_key UNIQUE (ticker, trade_date);


--
-- Name: filing_summaries filing_summaries_accession_number_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.filing_summaries
    ADD CONSTRAINT filing_summaries_accession_number_key UNIQUE (accession_number);


--
-- Name: filing_summaries_aud filing_summaries_aud_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.filing_summaries_aud
    ADD CONSTRAINT filing_summaries_aud_pkey PRIMARY KEY (rev, id);


--
-- Name: filing_summaries filing_summaries_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.filing_summaries
    ADD CONSTRAINT filing_summaries_pkey PRIMARY KEY (id);


--
-- Name: index_members_aud index_members_aud_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.index_members_aud
    ADD CONSTRAINT index_members_aud_pkey PRIMARY KEY (rev, id);


--
-- Name: index_members index_members_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.index_members
    ADD CONSTRAINT index_members_pkey PRIMARY KEY (id);


--
-- Name: listing_index_metrics_aud listing_index_metrics_aud_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.listing_index_metrics_aud
    ADD CONSTRAINT listing_index_metrics_aud_pkey PRIMARY KEY (rev, id);


--
-- Name: listing_index_metrics listing_index_metrics_listing_id_year_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.listing_index_metrics
    ADD CONSTRAINT listing_index_metrics_listing_id_year_key UNIQUE (listing_id, year);


--
-- Name: listing_index_metrics listing_index_metrics_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.listing_index_metrics
    ADD CONSTRAINT listing_index_metrics_pkey PRIMARY KEY (id);


--
-- Name: listings_aud listings_aud_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.listings_aud
    ADD CONSTRAINT listings_aud_pkey PRIMARY KEY (rev, id);


--
-- Name: listings listings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.listings
    ADD CONSTRAINT listings_pkey PRIMARY KEY (id);


--
-- Name: listings listings_ticker_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.listings
    ADD CONSTRAINT listings_ticker_key UNIQUE (ticker);


--
-- Name: market_indexes_aud market_indexes_aud_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.market_indexes_aud
    ADD CONSTRAINT market_indexes_aud_pkey PRIMARY KEY (rev, id);


--
-- Name: market_indexes market_indexes_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.market_indexes
    ADD CONSTRAINT market_indexes_code_key UNIQUE (code);


--
-- Name: market_indexes market_indexes_display_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.market_indexes
    ADD CONSTRAINT market_indexes_display_name_key UNIQUE (display_name);


--
-- Name: market_indexes market_indexes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.market_indexes
    ADD CONSTRAINT market_indexes_pkey PRIMARY KEY (id);


--
-- Name: quarters quarters_asset_id_year_quarter_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quarters
    ADD CONSTRAINT quarters_asset_id_year_quarter_key UNIQUE (asset_id, year, quarter);


--
-- Name: quarters_aud quarters_aud_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quarters_aud
    ADD CONSTRAINT quarters_aud_pkey PRIMARY KEY (rev, id);


--
-- Name: quarters quarters_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quarters
    ADD CONSTRAINT quarters_pkey PRIMARY KEY (id);


--
-- Name: revinfo revinfo_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.revinfo
    ADD CONSTRAINT revinfo_pkey PRIMARY KEY (rev);


--
-- Name: index_members fk13ivh2o6qxdnhpx5f4mc7n7x5; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.index_members
    ADD CONSTRAINT fk13ivh2o6qxdnhpx5f4mc7n7x5 FOREIGN KEY (listing_id) REFERENCES public.listings(id);


--
-- Name: filing_summaries_aud fk3xbwkkfkaf0ygy4cdujg9kemx; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.filing_summaries_aud
    ADD CONSTRAINT fk3xbwkkfkaf0ygy4cdujg9kemx FOREIGN KEY (rev) REFERENCES public.revinfo(rev);


--
-- Name: assets_aud fk5smxd9xxni14gcjvkgrxl7wqp; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assets_aud
    ADD CONSTRAINT fk5smxd9xxni14gcjvkgrxl7wqp FOREIGN KEY (rev) REFERENCES public.revinfo(rev);


--
-- Name: listing_index_metrics fk6pxrpwhgelxfxl85px28jht4t; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.listing_index_metrics
    ADD CONSTRAINT fk6pxrpwhgelxfxl85px28jht4t FOREIGN KEY (listing_id) REFERENCES public.listings(id);


--
-- Name: listings_aud fk7kshlfqa2i3q0pltql0817dmr; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.listings_aud
    ADD CONSTRAINT fk7kshlfqa2i3q0pltql0817dmr FOREIGN KEY (rev) REFERENCES public.revinfo(rev);


--
-- Name: market_indexes_aud fk84i40mem00v17il6ms3fp5wt3; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.market_indexes_aud
    ADD CONSTRAINT fk84i40mem00v17il6ms3fp5wt3 FOREIGN KEY (rev) REFERENCES public.revinfo(rev);


--
-- Name: index_members fk8lyi947l03uc12bsvmbhjkkq7; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.index_members
    ADD CONSTRAINT fk8lyi947l03uc12bsvmbhjkkq7 FOREIGN KEY (market_index_id) REFERENCES public.market_indexes(id);


--
-- Name: quarters fkb4ax0tx0x7uksms79ot6svibj; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quarters
    ADD CONSTRAINT fkb4ax0tx0x7uksms79ot6svibj FOREIGN KEY (asset_id) REFERENCES public.assets(id);


--
-- Name: listings fkcw7ikuehsaksky7w2yu2y8846; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.listings
    ADD CONSTRAINT fkcw7ikuehsaksky7w2yu2y8846 FOREIGN KEY (asset_id) REFERENCES public.assets(id);


--
-- Name: daily_prices_aud fkd4mb3ch4at02jegh7htde3itf; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.daily_prices_aud
    ADD CONSTRAINT fkd4mb3ch4at02jegh7htde3itf FOREIGN KEY (rev) REFERENCES public.revinfo(rev);


--
-- Name: corporate_actions_aud fkdfg9j8t5s8fwnf6yo3dpiprd9; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.corporate_actions_aud
    ADD CONSTRAINT fkdfg9j8t5s8fwnf6yo3dpiprd9 FOREIGN KEY (rev) REFERENCES public.revinfo(rev);


--
-- Name: listing_index_metrics_aud fkl1wf118xvjsghnd7pdjwy8vyq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.listing_index_metrics_aud
    ADD CONSTRAINT fkl1wf118xvjsghnd7pdjwy8vyq FOREIGN KEY (rev) REFERENCES public.revinfo(rev);


--
-- Name: quarters_aud fkpcxl1qwh7owqc7uwcdcmg0btl; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quarters_aud
    ADD CONSTRAINT fkpcxl1qwh7owqc7uwcdcmg0btl FOREIGN KEY (rev) REFERENCES public.revinfo(rev);


--
-- Name: filing_summaries fkrthyyfls829c85xpvb6e2s7ek; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.filing_summaries
    ADD CONSTRAINT fkrthyyfls829c85xpvb6e2s7ek FOREIGN KEY (asset_id) REFERENCES public.assets(id);


--
-- Name: index_members_aud fku595gwe9kayelbq5a9h4c6qq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.index_members_aud
    ADD CONSTRAINT fku595gwe9kayelbq5a9h4c6qq FOREIGN KEY (rev) REFERENCES public.revinfo(rev);


--
-- End of initial schema
