--
-- Per-accession cache of corporate-action text extractions. SEC filings are immutable, so
-- record-date / ex-date / declaration-tuple / split-date extraction results are persisted once
-- per accession and re-scans only fetch documents for accessions not yet extracted (or extracted
-- with an older extractor version).
--

CREATE TABLE public.filing_extractions (
    id bigint NOT NULL,
    cik bigint NOT NULL,
    accession_number character varying(40) NOT NULL,
    filing_date date,
    form_type character varying(20),
    dividend_extractor_version integer,
    split_extractor_version integer,
    best_record_date date,
    best_record_date_score integer,
    ex_date_candidates_json text,
    declarations_json text,
    best_split_date date,
    best_split_date_score integer,
    extracted_at timestamp without time zone
);

ALTER TABLE public.filing_extractions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.filing_extractions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.filing_extractions
    ADD CONSTRAINT filing_extractions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.filing_extractions
    ADD CONSTRAINT filing_extractions_cik_accession_key UNIQUE (cik, accession_number);
