# Generated by Django 5.0.4 on 2024-06-26 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=1000)),
                ('marketCap', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('country', models.CharField(default='United States', max_length=1000)),
            ],
        ),
    ]
