# Generated by Django 5.0.4 on 2024-06-27 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexCompare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='marketCap',
            field=models.DecimalField(decimal_places=100, default=1, max_digits=100),
        ),
    ]
