# Generated by Django 5.0.4 on 2024-06-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexCompare', '0002_alter_stock_marketcap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='marketCap',
            field=models.DecimalField(decimal_places=10, max_digits=100),
        ),
    ]
