# Generated by Django 5.0.4 on 2024-06-28 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexCompare', '0003_alter_stock_marketcap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='marketCap',
            field=models.DecimalField(decimal_places=0, max_digits=100),
        ),
    ]
