# Generated by Django 5.0.4 on 2024-07-05 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexCompare', '0004_alter_stock_marketcap'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=200)),
                ('percent', models.DecimalField(decimal_places=5, max_digits=100)),
                ('index', models.CharField(max_length=1000)),
            ],
        ),
    ]
