# Generated by Django 5.0.4 on 2024-07-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexCompare', '0005_indexmember'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='country',
            new_name='countryHQ',
        ),
        migrations.AddField(
            model_name='stock',
            name='countryIncorp',
            field=models.CharField(default='United States', max_length=1000),
        ),
    ]
