# Generated by Django 5.0.4 on 2024-07-31 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexCompare', '0007_stock_securitytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='freeFloat',
            field=models.DecimalField(decimal_places=5, default=100, max_digits=100),
        ),
        migrations.AddField(
            model_name='stock',
            name='volume',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=100),
        ),
    ]
