# Generated by Django 5.0.4 on 2024-08-07 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexCompare', '0010_stock_freefloatmarketcap'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=1000)),
                ('marketCap', models.DecimalField(decimal_places=0, max_digits=100)),
                ('volume', models.DecimalField(decimal_places=0, default=0, max_digits=100)),
                ('volumeUSD', models.DecimalField(decimal_places=0, default=0, max_digits=100)),
                ('freeFloat', models.DecimalField(decimal_places=5, default=100, max_digits=100)),
                ('freeFloatMarketCap', models.DecimalField(decimal_places=0, default=0, max_digits=100)),
                ('countryIncorp', models.CharField(default='United States', max_length=1000)),
                ('countryHQ', models.CharField(default='United States', max_length=1000)),
                ('securityType', models.CharField(default='Common Stock', max_length=1000)),
            ],
        ),
    ]
