# Generated by Django 5.0.4 on 2024-08-07 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexCompare', '0011_outliers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Outliers',
            new_name='Outlier',
        ),
    ]
