# Generated by Django 5.0.4 on 2024-08-29 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexCompare', '0012_rename_outliers_outlier'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlier',
            name='yearIPO',
            field=models.IntegerField(default=0, max_length=4),
        ),
        migrations.AddField(
            model_name='stock',
            name='yearIPO',
            field=models.IntegerField(default=0, max_length=4),
        ),
    ]
