# Generated by Django 5.0.4 on 2024-08-29 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexCompare', '0013_outlier_yearipo_stock_yearipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlier',
            name='yearIPO',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='yearIPO',
            field=models.IntegerField(default=0),
        ),
    ]
