# Generated by Django 5.0.4 on 2024-08-29 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexCompare', '0014_alter_outlier_yearipo_alter_stock_yearipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlier',
            name='name',
            field=models.CharField(max_length=100000),
        ),
    ]
