# Generated by Django 5.0.4 on 2024-08-29 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexCompare', '0015_alter_outlier_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlier',
            name='notes',
            field=models.CharField(default='', max_length=100000),
        ),
        migrations.AlterField(
            model_name='outlier',
            name='name',
            field=models.CharField(max_length=1000),
        ),
    ]
