# Generated by Django 5.0.4 on 2024-09-14 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexCompare', '0017_historicalindexmember_historicaloutlier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalindexmember',
            name='stock',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexCompare.stock'),
        ),
        migrations.AddField(
            model_name='indexmember',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='indexCompare.stock'),
        ),
    ]
