# Generated by Django 5.0.4 on 2024-09-14 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexCompare', '0018_historicalindexmember_stock_indexmember_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexmember',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexCompare.stock'),
        ),
    ]
