# Generated by Django 5.0.4 on 2024-10-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexCompare', '0019_alter_indexmember_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalindexmember',
            name='notes',
            field=models.CharField(default='', max_length=100000),
        ),
        migrations.AddField(
            model_name='historicalindexmember',
            name='outlier',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='indexmember',
            name='notes',
            field=models.CharField(default='', max_length=100000),
        ),
        migrations.AddField(
            model_name='indexmember',
            name='outlier',
            field=models.BooleanField(default=False),
        ),
    ]
