# Generated by Django 5.0.4 on 2024-10-05 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexCompare', '0020_historicalindexmember_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalindexmember',
            name='ticker',
        ),
        migrations.RemoveField(
            model_name='indexmember',
            name='ticker',
        ),
    ]
