# Generated by Django 5.0.4 on 2024-12-08 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexCompare', '0021_remove_historicalindexmember_ticker_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaloutlier',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='Outlier',
        ),
        migrations.DeleteModel(
            name='HistoricalOutlier',
        ),
    ]
