# Generated by Django 4.1.7 on 2023-10-29 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_allocation_target'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.DecimalField(decimal_places=0, max_digits=15)),
                ('account1', models.CharField(choices=[('RIRA', 'Roth IRA'), ('TIRA', 'Trad IRA'), ('401k', '401k'), ('TAXD', 'Taxable')], default='TAXD', max_length=4)),
                ('account2', models.CharField(choices=[('RIRA', 'Roth IRA'), ('TIRA', 'Trad IRA'), ('401k', '401k'), ('TAXD', 'Taxable')], default='TAXD', max_length=4)),
                ('account3', models.CharField(choices=[('RIRA', 'Roth IRA'), ('TIRA', 'Trad IRA'), ('401k', '401k'), ('TAXD', 'Taxable')], default='TAXD', max_length=4)),
            ],
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='account',
            new_name='account_text',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='user',
            new_name='user_key',
        ),
    ]
