# Generated by Django 4.1.7 on 2023-12-15 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_delete_allocation_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='user_key',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='asset',
            name='shares_number',
            field=models.DecimalField(decimal_places=5, max_digits=25),
        ),
    ]
