# Generated by Django 5.0.4 on 2024-10-08 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_snp500price_historicalasset_historicalsnp500price'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='SnP500Price',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portfolio.snp500price'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalasset',
            name='SnP500Price',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='portfolio.snp500price'),
        ),
    ]
