# Generated by Django 5.0.4 on 2025-01-08 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_asset_snp500price_historicalasset_snp500price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='buy',
            new_name='buyDate',
        ),
        migrations.RenameField(
            model_name='historicalasset',
            old_name='buy',
            new_name='buyDate',
        ),
    ]
