# Generated by Django 5.0.4 on 2025-01-10 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_asset_dividends_asset_reinvestshares_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='dividends',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='reinvestShares',
        ),
        migrations.RemoveField(
            model_name='historicalasset',
            name='dividends',
        ),
        migrations.RemoveField(
            model_name='historicalasset',
            name='reinvestShares',
        ),
        migrations.RemoveField(
            model_name='historicalsnp500price',
            name='dividends',
        ),
        migrations.RemoveField(
            model_name='historicalsnp500price',
            name='reinvestShares',
        ),
        migrations.RemoveField(
            model_name='snp500price',
            name='dividends',
        ),
        migrations.RemoveField(
            model_name='snp500price',
            name='reinvestShares',
        ),
    ]
