# Generated by Django 5.0.4 on 2025-03-16 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_remove_asset_dividends_remove_asset_reinvestshares_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='buyDate',
            new_name='buy_date',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='costbasis',
            new_name='cost_basis',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='SnP500Price',
            new_name='snp500_buy_date',
        ),
        migrations.RenameField(
            model_name='historicalasset',
            old_name='buyDate',
            new_name='buy_date',
        ),
        migrations.RenameField(
            model_name='historicalasset',
            old_name='costbasis',
            new_name='cost_basis',
        ),
        migrations.RenameField(
            model_name='historicalasset',
            old_name='SnP500Price',
            new_name='snp500_buy_date',
        ),
    ]
