# Generated by Django 5.0.4 on 2025-03-16 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_rename_buydate_asset_buy_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='sell_date',
            field=models.DateField(blank=True, null=True, verbose_name='date sold'),
        ),
        migrations.AddField(
            model_name='asset',
            name='snp500_sell_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets_sold', to='portfolio.snp500price'),
        ),
        migrations.AddField(
            model_name='historicalasset',
            name='sell_date',
            field=models.DateField(blank=True, null=True, verbose_name='date sold'),
        ),
        migrations.AddField(
            model_name='historicalasset',
            name='snp500_sell_date',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='portfolio.snp500price'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='snp500_buy_date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets_bought', to='portfolio.snp500price'),
        ),
    ]
