# Generated by Django 5.0.4 on 2025-03-17 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_asset_sell_date_asset_snp500_sell_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='sell_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='historicalasset',
            name='sell_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='cost_basis',
            field=models.DecimalField(decimal_places=2, max_digits=25),
        ),
        migrations.AlterField(
            model_name='historicalasset',
            name='cost_basis',
            field=models.DecimalField(decimal_places=2, max_digits=25),
        ),
    ]
