# Generated by Django 5.0.4 on 2025-03-29 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_asset_sell_price_historicalasset_sell_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=5)),
                ('short_name', models.CharField(max_length=100)),
                ('long_name', models.CharField(max_length=250)),
                ('type', models.CharField(choices=[('EQUITY', 'Equity'), ('ETF', 'ETF'), ('MUTUAL_FUND', 'Mutual Fund')], max_length=25)),
                ('exchange', models.CharField(choices=[('NYSE', 'New York Stock Exchange'), ('NASDAQ', 'NASDAQ'), ('LSE', 'London Stock Exchange'), ('TSE', 'Tokyo Stock Exchange')], max_length=25)),
                ('market', models.CharField(choices=[('us_market', 'United States')], max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.assetinfo'),
        ),
        migrations.AddField(
            model_name='historicalasset',
            name='asset_info',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='portfolio.assetinfo'),
        ),
    ]
