# Generated by Django 5.0.4 on 2025-03-29 14:27

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_assetinfo_asset_asset_info_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalAssetInfo',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('ticker', models.CharField(max_length=5)),
                ('short_name', models.CharField(max_length=100)),
                ('long_name', models.CharField(max_length=250)),
                ('type', models.CharField(choices=[('EQUITY', 'Equity'), ('ETF', 'ETF'), ('MUTUAL_FUND', 'Mutual Fund')], max_length=25)),
                ('exchange', models.CharField(choices=[('NYSE', 'New York Stock Exchange'), ('NASDAQ', 'NASDAQ'), ('LSE', 'London Stock Exchange'), ('TSE', 'Tokyo Stock Exchange')], max_length=25)),
                ('market', models.CharField(choices=[('us_market', 'United States')], max_length=25)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical asset info',
                'verbose_name_plural': 'historical asset infos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
