# Generated by Django 5.0.4 on 2025-03-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_historicalassetinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetinfo',
            name='ticker',
            field=models.CharField(db_index=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalassetinfo',
            name='ticker',
            field=models.CharField(db_index=True, max_length=5),
        ),
    ]
