# Generated by Django 5.0.4 on 2025-07-26 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0021_remove_asset_ticker_remove_historicalasset_ticker_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalasset',
            name='snp500_sell_date',
        ),
        migrations.RemoveField(
            model_name='historicalasset',
            name='snp500_buy_date',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='snp500_buy_date',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='snp500_sell_date',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='cost_basis',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='sell_price',
        ),
        migrations.RemoveField(
            model_name='historicalasset',
            name='cost_basis',
        ),
        migrations.RemoveField(
            model_name='historicalasset',
            name='sell_price',
        ),
        migrations.DeleteModel(
            name='HistoricalSnP500Price',
        ),
        migrations.DeleteModel(
            name='SnP500Price',
        ),
    ]
