# Generated by Django 5.0.4 on 2025-07-29 00:59

from django.db import migrations, models

# Manually Added
def copy_ticker_to_asset_and_history(apps, schema_editor):
    Asset = apps.get_model('portfolio', 'Asset')
    HistoricalAsset = apps.get_model('portfolio', 'HistoricalAsset')

    for asset in Asset.objects.select_related('asset_info'):
        if asset.asset_info and asset.asset_info.ticker:
            asset.ticker = asset.asset_info.ticker
            asset.save()

            # Update historical rows for this asset
            historicals = HistoricalAsset.objects.filter(id=asset.id)
            for h in historicals:
                h.ticker = asset.asset_info.ticker
                h.save()

class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0022_remove_historicalasset_snp500_sell_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='ticker',
            field=models.CharField(default='AAPL', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalasset',
            name='ticker',
            field=models.CharField(default='AAPL', max_length=5),
            preserve_default=False,
        ),
        migrations.RunPython(copy_ticker_to_asset_and_history),
    ]
