# Generated by Django 5.0.4 on 2025-07-29 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0023_asset_ticker_historicalasset_ticker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='asset_info',
        ),
        migrations.RemoveField(
            model_name='historicalasset',
            name='asset_info',
        ),
        migrations.RemoveField(
            model_name='historicalassetinfo',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='AssetInfo',
        ),
        migrations.DeleteModel(
            name='HistoricalAssetInfo',
        ),
    ]
