# Generated by Django 5.0.4 on 2026-01-22 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0025_account_asset_account_historicalasset_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('ROTH_IRA', 'Roth IRA'), ('TRADITIONAL_IRA', 'Traditional IRA'), ('TAXABLE_ACCOUNT', 'Taxable Account'), ('ROTH_401K', 'Roth 401k'), ('TRADITIONAL_401K', 'Traditional 401k'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalaccount',
            name='account_type',
            field=models.CharField(choices=[('ROTH_IRA', 'Roth IRA'), ('TRADITIONAL_IRA', 'Traditional IRA'), ('TAXABLE_ACCOUNT', 'Taxable Account'), ('ROTH_401K', 'Roth 401k'), ('TRADITIONAL_401K', 'Traditional 401k'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
