# Generated by Django 5.0.4 on 2026-04-15 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('BOOK', 'Book'), ('MOVIE', 'Movie'), ('SHOW', 'TV Show'), ('MUSIC', 'Music'), ('PODCAST', 'Podcast'), ('GAME', 'Game')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='recommendation',
            constraint=models.UniqueConstraint(fields=('type', 'title', 'artist'), name='uniq_recommendation'),
        ),
    ]
