# Generated by Django 5.0.4 on 2026-04-16 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='type',
            field=models.CharField(choices=[('BOOK', 'Book'), ('MOVIE', 'Movie'), ('SHOW', 'TV Show'), ('MUSIC', 'Music'), ('PODCAST', 'Podcast'), ('GAME', 'Game'), ('WEBSITE', 'Website')], max_length=10),
        ),
    ]
